export default function ClientCardComponent({client}){
    return(
        <div>
            <p>
                <span>
                    Nome:
                </span>
                {client.nome}
            </p>
            <p>
                <span>
                    Cpf:
                </span>
                {client.cpf}
            </p>
            <p>
                <span>
                    Email:
                </span>
                {client.email}
            </p>
            <p>
                <span>
                    Idade:
                </span>
                {client.idade}
            </p>
        </div>
    )
}